
[auth.email.template.confirmation]
subject = "Welkom bij de KSA app! Bevestig je account 🚀"
content_path = "./templates/confirmation.html"

[auth.email.template.recovery]
subject = "Wachtwoord herstellen voor KSA app"
content_path = "./templates/recovery.html"

[functions.google-sheets-sync]
enabled = true
verify_jwt = true
import_map = "./functions/google-sheets-sync/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/google-sheets-sync/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/google-sheets-sync/*.html" ]
