-- =====================================================================
-- Drank en strepen (CLAUDE.md: Drank en strepen)
--  - prijs per streep wordt bewaard op het moment van strepen
--  - voorraad per drank daalt automatisch bij elke streep; Drankteam corrigeert na telling
--  - Drankteam sluit een periode af: per leider een echte factuur met gestructureerde mededeling
--  - één berekening voor saldo, preview en factuur: periode_overzicht()
--  - ranking van de huidige periode, zichtbaar voor alle leiding (enkel totalen)
-- Vereist: 20261001000100_rollen_en_rechten.sql en 20261001000200_rls_policies.sql
-- =====================================================================

begin;

-- ---------------------------------------------------------------------
-- 1. Prijs per streep
-- ---------------------------------------------------------------------
alter table public.consumpties add column if not exists prijs numeric(6,2);

update public.consumpties c
set prijs = d.prijs
from public.dranken d
where d.id = c.drank_id and c.prijs is null;

create or replace function public.consumptie_zet_prijs()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.prijs is null then
    select prijs into new.prijs from dranken where id = new.drank_id;
  end if;
  return new;
end;
$$;

drop trigger if exists consumptie_zet_prijs on public.consumpties;
create trigger consumptie_zet_prijs
  before insert on public.consumpties
  for each row execute function public.consumptie_zet_prijs();

-- ---------------------------------------------------------------------
-- 2. Voorraad volgt de strepen automatisch
-- ---------------------------------------------------------------------
create or replace function public.consumptie_voorraad()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if tg_op in ('UPDATE', 'DELETE') then
    update dranken set huidige_voorraad = huidige_voorraad + old.aantal where id = old.drank_id;
  end if;
  if tg_op in ('INSERT', 'UPDATE') then
    update dranken set huidige_voorraad = huidige_voorraad - new.aantal where id = new.drank_id;
  end if;
  return null;
end;
$$;

drop trigger if exists consumptie_voorraad on public.consumpties;
create trigger consumptie_voorraad
  after insert or delete or update of aantal, drank_id on public.consumpties
  for each row execute function public.consumptie_voorraad();

create table if not exists public.voorraad_correcties (
  id uuid primary key default gen_random_uuid(),
  drank_id uuid not null references public.dranken(id) on delete cascade,
  oude_voorraad integer not null,
  nieuwe_voorraad integer not null,
  notitie text,
  door uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

alter table public.voorraad_correcties enable row level security;
create policy "drankteam ziet correcties" on public.voorraad_correcties for select using (public.heeft_recht('drank_beheren'));

-- Na een manuele telling: zet de voorraad en log de correctie
create or replace function public.corrigeer_voorraad(p_drank_id uuid, p_nieuwe_voorraad integer, p_notitie text default null)
returns void language plpgsql security definer set search_path = public as $$
declare v_oud integer;
begin
  if not public.heeft_recht('drank_beheren') then
    raise exception 'Enkel Drankteam mag de voorraad corrigeren';
  end if;
  select huidige_voorraad into v_oud from dranken where id = p_drank_id for update;
  if not found then raise exception 'Onbekende drank'; end if;
  update dranken set huidige_voorraad = p_nieuwe_voorraad where id = p_drank_id;
  insert into voorraad_correcties (drank_id, oude_voorraad, nieuwe_voorraad, notitie, door)
  values (p_drank_id, v_oud, p_nieuwe_voorraad, p_notitie, auth.uid());
end;
$$;

-- ---------------------------------------------------------------------
-- 3. Facturen
-- ---------------------------------------------------------------------
alter table public.facturen add column if not exists period_id uuid references public.billing_periods(id) on delete set null;
alter table public.facturen add column if not exists nummer bigint generated by default as identity;
alter table public.facturen add column if not exists mededeling text;
alter table public.facturen add column if not exists aantal_strepen integer not null default 0;
alter table public.facturen add column if not exists drank_bedrag numeric(10,2) not null default 0;
alter table public.facturen add column if not exists friet_bedrag numeric(10,2) not null default 0;
alter table public.facturen add column if not exists correctie_bedrag numeric(10,2) not null default 0;
alter table public.facturen add column if not exists betaald_op timestamptz;

alter table public.frituur_bestellingen add column if not exists factuur_id uuid references public.facturen(id) on delete set null;

-- Belgische gestructureerde mededeling (+++123/4567/89012+++): 10 cijfers + controlegetal modulo 97
create or replace function public.gestructureerde_mededeling(p_nummer bigint)
returns text language sql immutable as $$
  with basis as (select lpad((p_nummer % 10000000000)::text, 10, '0') as b),
  controle as (select b, case when (b::bigint % 97) = 0 then 97 else (b::bigint % 97) end as c from basis)
  select '+++' || substr(b, 1, 3) || '/' || substr(b, 4, 4) || '/' || substr(b, 8, 3) || lpad(c::text, 2, '0') || '+++'
  from controle;
$$;

update public.facturen set mededeling = public.gestructureerde_mededeling(nummer) where mededeling is null;

-- Betaald zetten bewaart ook de datum
create or replace function public.factuur_betaald_op()
returns trigger language plpgsql as $$
begin
  if new.status = 'betaald' and old.status is distinct from 'betaald' then
    new.betaald_op := now();
  elsif new.status <> 'betaald' then
    new.betaald_op := null;
  end if;
  return new;
end;
$$;

drop trigger if exists factuur_betaald_op on public.facturen;
create trigger factuur_betaald_op
  before update of status on public.facturen
  for each row execute function public.factuur_betaald_op();

-- ---------------------------------------------------------------------
-- 4. Eén berekening: wat is elke leider verschuldigd voor de (open) periode?
--    - geschatte_kost > 0: kostendeling (geschatte kost / totaal strepen in de periode)
--    - anders: aantal x prijs op het moment van strepen
--    - plus friet en correcties van de periode
--    Gewone leiding ziet enkel de eigen rij; Drankteam ziet iedereen.
-- ---------------------------------------------------------------------
create or replace function public.periode_overzicht(p_period_id uuid default null)
returns table (
  user_id uuid, naam text, strepen bigint,
  drank_bedrag numeric, friet_bedrag numeric, correctie_bedrag numeric, totaal numeric
)
language plpgsql stable security definer set search_path = public as $$
declare
  v_period uuid;
  v_geschat numeric;
  v_totaal_strepen numeric;
  v_per_streep numeric;
  v_alles boolean := public.heeft_recht('drank_beheren');
begin
  if not public.is_leiding() then
    return;
  end if;

  v_period := coalesce(p_period_id, (select id from billing_periods where not is_closed order by start_datum desc limit 1));
  select coalesce(geschatte_kost, 0) into v_geschat from billing_periods where id = v_period;

  select coalesce(sum(aantal), 0) into v_totaal_strepen
  from consumpties
  where factuur_id is null and (period_id = v_period or period_id is null);

  v_per_streep := case when coalesce(v_geschat, 0) > 0 and v_totaal_strepen > 0 then v_geschat / v_totaal_strepen end;

  return query
  with c as (
    select c.user_id, sum(c.aantal) as strepen, sum(c.aantal * coalesce(c.prijs, d.prijs, 0)) as volgens_prijs
    from consumpties c left join dranken d on d.id = c.drank_id
    where c.factuur_id is null and (c.period_id = v_period or c.period_id is null)
    group by c.user_id
  ),
  f as (
    select b.user_id, sum(coalesce(b.totaal_prijs, 0)) as bedrag
    from frituur_bestellingen b
    where b.factuur_id is null and (b.period_id = v_period or b.period_id is null)
    group by b.user_id
  ),
  k as (
    select bc.user_id, sum(bc.correctie_bedrag) as bedrag
    from billing_corrections bc
    where bc.period_id = v_period
    group by bc.user_id
  ),
  ids as (select c.user_id from c union select f.user_id from f union select k.user_id from k)
  select
    ids.user_id,
    p.naam,
    coalesce(c.strepen, 0)::bigint,
    round(coalesce(case when v_per_streep is not null then c.strepen * v_per_streep else c.volgens_prijs end, 0), 2),
    round(coalesce(f.bedrag, 0), 2),
    round(coalesce(k.bedrag, 0), 2),
    round(
      coalesce(case when v_per_streep is not null then c.strepen * v_per_streep else c.volgens_prijs end, 0)
      + coalesce(f.bedrag, 0) + coalesce(k.bedrag, 0), 2)
  from ids
  join profiles p on p.id = ids.user_id
  left join c on c.user_id = ids.user_id
  left join f on f.user_id = ids.user_id
  left join k on k.user_id = ids.user_id
  where v_alles or ids.user_id = auth.uid();
end;
$$;

-- ---------------------------------------------------------------------
-- 5. Periode afsluiten: per leider een factuur, strepen/friet gekoppeld, nieuwe periode open
-- ---------------------------------------------------------------------
create or replace function public.sluit_periode_af(p_period_id uuid default null)
returns json language plpgsql security definer set search_path = public as $$
declare
  v_period billing_periods%rowtype;
  v_nieuw uuid;
  v_factuur uuid;
  v_aantal integer := 0;
  r record;
  v_start date := current_date;
  v_werkjaar text;
begin
  if not public.heeft_recht('drank_beheren') then
    raise exception 'Enkel Drankteam mag een periode afsluiten';
  end if;

  select * into v_period from billing_periods
  where id = coalesce(p_period_id, (select id from billing_periods where not is_closed order by start_datum desc limit 1))
  for update;
  if not found then raise exception 'Geen open periode gevonden'; end if;
  if v_period.is_closed then raise exception 'Deze periode is al afgesloten'; end if;

  for r in select * from public.periode_overzicht(v_period.id) loop
    if r.strepen = 0 and r.totaal = 0 then continue; end if;

    insert into facturen (user_id, user_naam, totaal_bedrag, periode, status, period_id,
                          aantal_strepen, drank_bedrag, friet_bedrag, correctie_bedrag)
    values (r.user_id, r.naam, r.totaal, v_period.naam, 'onbetaald', v_period.id,
            r.strepen, r.drank_bedrag, r.friet_bedrag, r.correctie_bedrag)
    returning id into v_factuur;

    update facturen set mededeling = public.gestructureerde_mededeling(nummer) where id = v_factuur;

    update consumpties set factuur_id = v_factuur
    where user_id = r.user_id and factuur_id is null and (period_id = v_period.id or period_id is null);

    update frituur_bestellingen set factuur_id = v_factuur
    where user_id = r.user_id and factuur_id is null and (period_id = v_period.id or period_id is null);

    v_aantal := v_aantal + 1;
  end loop;

  update billing_periods set is_closed = true, eind_datum = now() where id = v_period.id;

  -- Werkjaar loopt vanaf 15 augustus
  v_werkjaar := case
    when extract(month from v_start) < 8 or (extract(month from v_start) = 8 and extract(day from v_start) < 15)
      then (extract(year from v_start) - 1)::int || '-' || extract(year from v_start)::int
    else extract(year from v_start)::int || '-' || (extract(year from v_start) + 1)::int
  end;

  insert into billing_periods (naam, start_datum, is_closed, geschatte_kost, werkjaar)
  values ('Periode vanaf ' || to_char(v_start, 'DD/MM/YYYY'), now(), false, 0, v_werkjaar)
  returning id into v_nieuw;

  return json_build_object('closed_period_id', v_period.id, 'new_period_id', v_nieuw, 'aantal_facturen', v_aantal);
end;
$$;

-- ---------------------------------------------------------------------
-- 6. Ranking huidige periode (enkel totalen, voor alle leiding)
-- ---------------------------------------------------------------------
create or replace function public.ranking_huidige_periode()
returns table (user_id uuid, naam text, strepen bigint)
language sql stable security definer set search_path = public as $$
  select c.user_id, coalesce(nullif(p.nickname, ''), p.naam), sum(c.aantal)::bigint
  from consumpties c
  join profiles p on p.id = c.user_id
  where public.is_leiding() and c.factuur_id is null
  group by c.user_id, p.nickname, p.naam
  order by 3 desc;
$$;

-- ---------------------------------------------------------------------
-- 7. Rechten op de functies
-- ---------------------------------------------------------------------
revoke all on function public.corrigeer_voorraad(uuid, integer, text) from public, anon;
revoke all on function public.periode_overzicht(uuid) from public, anon;
revoke all on function public.sluit_periode_af(uuid) from public, anon;
revoke all on function public.ranking_huidige_periode() from public, anon;
grant execute on function public.corrigeer_voorraad(uuid, integer, text) to authenticated;
grant execute on function public.periode_overzicht(uuid) to authenticated;
grant execute on function public.sluit_periode_af(uuid) to authenticated;
grant execute on function public.ranking_huidige_periode() to authenticated;

-- De oude archive_consumpties_period (inhoud onbekend, maakte geen facturen) niet meer aanroepbaar vanuit de app
do $$
begin
  if to_regprocedure('public.archive_consumpties_period()') is not null then
    revoke execute on function public.archive_consumpties_period() from anon, authenticated;
  end if;
end $$;

commit;
